query Input {
  cart {
    lines {
      id
      quantity
      attribute(key: "_BundlePrice"){
        key
        value
      }
      merchandise {
        __typename
        ... on ProductVariant {
          id
          title
          component_parents: metafield(
            namespace: "custom"
            key: "component_parents"
          ) {
            value
          }
          component_reference: metafield(
            namespace: "custom"
            key: "component_reference"
          ) {
            value
          }
          component_quantities: metafield(
            namespace: "custom"
            key: "component_quantities"
          ) {
            value
          }
          product {
            bundle_type: metafield(
              namespace: "$app:bundleType"
              key: "bundleType-configuration"
            ) {
              value
            }
          }
        }
      }
    }
  }
}